tomplus/main/routes.py
from flask import render_template, request, Blueprint
from tomplus.models import Fanart, Post, TV_Videos

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    fanart = Fanart.query.order_by(Fanart.id)
    return render_template('main/home.html', fanart=fanart)

@main.route("/about")
def about():
    return render_template('main/about.html', title='About')

@main.route("/content")
def content():
    return render_template('main/content.html', title='Content')

@main.route("/announcements")
def announcements():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('main/announcements.html', posts=posts, title='Announcements')

tomplus/misc/routes.py
from flask import Blueprint, render_template

misc = Blueprint('misc', __name__)

@misc.route("/discord")
def discord():
    return render_template('misc/discord.html', title="Discord Sign-up")


@misc.route("/this-isnt-merch")
def merch():
    return render_template('misc/merch.html', title="What's Happening?")

tomplus/users/routes.py
from flask import (render_template, url_for, flash, redirect,
                    request, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required                    
from tomplus import db, bcrypt
from tomplus.models import User, Post, Fanart, TS_Videos
from tomplus.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                    RequestResetForm, ResetPasswordForm, AddFanartForm)
from tomplus.users.utils import save_picture, send_reset_email, save_art

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)

    art_form = AddFanartForm()
    if art_form.image.data:
        artist_image = save_art(art_form.image.data)
        new_art = Fanart(image=artist_image, artist=art_form.artist.data)
        db.session.add(new_art)
        db.session.commit()
        flash('New art added to homepage!', 'success')
        return redirect(url_for('users.account'))

    return render_template('account.html', title='Account',
                           image_file=image_file, form=form, art_form=art_form)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)

    
        
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

tomplus/templates/main/about.html
{% extends "bases/base_home.html" %}
{% block content %}
        <div style="height: 388px; width: 100%;">
            <div class="container-fluid about-bg-img"></div>
            <div class="container-fluid home-bg-text text-center">
              <h1 class="home-title" style="color:#eceae5;">ABOUT ME</h1>
            </div>
        </div>
        <div style="height: 100px">
            <div class="ribbon" style="background-color: #5a7876; top: 469px;"></div>
            <div class="ribbon" style="background-color: #acccc6; top: 519px;"></div>
        </div>
  <div style="background-color: #2c2c2c; display: table; margin-left: auto; margin-right: auto; width: 60rem;">
    <ul class="timeline">
      <li>
        <div class="timeline-panel">
          <div class="timeline-heading">
            <h3 class="timeline-title">In The Beginning</h3>
            <p class="text-muted" style="color: antiquewhite">February 2013</p>
          </div>
          <div class="timeline-body">
            <p>At the young age of 9, Tom creates his first YouTube channel, Channelnutpig.</p>
          </div>
        </div>
      </li>
      <li class="timeline-inverted">
        <div class="timeline-panel">
          <div class="timeline-heading">
            <h3 class="timeline-title">Dawn of the Twitch Streamer</h3>
            <p class="text-muted" style="color: antiquewhite">September 2018</p>
          </div>
          <div class="timeline-body">
            <p>Tom begins his Twitch career by regularly streaming games like PUBG, Fortnite, and Minecraft Hypixel.</p>
          </div>
        </div>
      </li>
      <li>
        <div class="timeline-panel">
          <div class="timeline-heading">
            <h3 class="timeline-title">Taking The First Steps</h3>
            <p class="text-muted" style="color: antiquewhite">Early 2019</p>
          </div>
          <div class="timeline-body">
            <p>With aide of his energetic personality, Tom becomes an affiliate with Twitch. 
              Soon after, he begins to gain traction on his Tommyinnit YouTube channel as he posts Hypixel Skyblock videos.</p>          </div>
        </div>
      </li>
      <li class="timeline-inverted">
        <div class="timeline-panel">
          <div class="timeline-heading">
            <h3 class="timeline-title">Joining the Community</h3>
            <p class="text-muted" style="color: antiquewhite">November 2019</p>
          </div>
          <div class="timeline-body">
            <p>Tom joins EarthSMP, a Minecraft multiplayer server full of popular Minecraft streamers and YouTubers. 
              Here he is quick to make friends and "enemies" on his journey to become the (not very) profitable nation of Business Bay.</p>          
            </div>
        </div>
      </li>
      <li>
        <div class="timeline-panel">
          <div class="timeline-heading">
            <h3 class="timeline-title">Breaking the Sound Barrier</h3>
            <p class="text-muted" style="color: antiquewhite">July 2020</p>
          </div>
          <div class="timeline-body">
            <p>The next few months are some of the biggest for Tom. Starting on July, he joins the DreamSMP, a Minecraft 
              multiplayer server populated by friends of the content creator Dream. With the aid of his partner in crime, 
              WilburSoot, the DreamSMP skyrockets in fame for its <i>Hamilton</i> inspired storyline. This is Tom's rise 
              in popularity gaining him over 4 million subscribers in the span of just 4 months.</p>          
            </div>
        </div>
      </li>
      <li class="timeline-inverted">
        <div class="timeline-panel">
          <div class="timeline-heading">
            <h3 class="timeline-title">Reaching the Top...</h3>
            <p class="text-muted" style="color: antiquewhite">January 2021</p>
          </div>
          <div class="timeline-body">
            <p>Streaming the finale of a storyline for the DreamSMP, Tom reaches peak viewership of over 650,000 viewers on Twitch,
              making the stream the third all time high of concurrent Twitch viewers on a stream.
            </p>          
          </div>
        </div>
      </li>
      <li>
        <div class="timeline-panel">
          <div class="timeline-heading">
            <h3 class="timeline-title">...And Going Beyond</h3>
            <p class="text-muted" style="color: antiquewhite">July 2021</p>
          </div>
          <div class="timeline-body">
            <p>Just a year after his initial gain of a million subscribers on YouTube, Tom surpasses the 10 million mark. 
              His content has expanded from Minecraft videos and streams to also including vlogs of the adventures he has 
              with friends in the UK.
            </p>
            </div>
        </div>
      </li>
      <li class="timeline-inverted">
        <div class="timeline-panel">
          <div class="timeline-heading">
            <h3 class="timeline-title">In The Moment</h3>
            <p class="text-muted" style="color: antiquewhite" >Today</p>
          </div>
          <div class="timeline-body">
            <p>Today Tom has amassed over 11 million subscribers on his main YouTube channel and 7 million followers on Twitch.
              His bright and energetic personality has made him a favorite in his communities, and he continues to take joy in
              content creation.
            </p>         
          </div>
        </div>
      </li>
  </ul>
  </div>
    <div class="ribbon" style="background-color: #acccc6; position: inherit;"></div>
    <div class="ribbon" style="background-color: #5a7876; position: inherit;"></div>
{% endblock content %}

tomplus/templates/main/announcements.html
{% extends "bases/base_home.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if posts.page == page_num %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.announcements', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.announcements', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
    {% endfor %}
{% endblock content %}

tomplus/templates/main/content.html
{% extends "bases/base_home.html" %}
{% block content %}
<body style="background-color: #eee5d5;">
    <div style="height: 388px; width: 100%;">
        <div class="container-fluid content-bg-img"></div>
        <div class="container-fluid home-bg-text text-center">
          <h1 class="home-title" style="color:#fbdcce;">CHANNELS</h1>
        </div>
    </div>
    <div style="height: 150px">
        <div class="ribbon" style="background-color: #c3848fce; top: 469px;"></div>
        <div class="ribbon" style="background-color: #e3b8b2; top: 519px;"></div>
    </div>

    <div class="ribbon-title"><h1>YOUTUBE</h1></div>
    <div class="row" style="height:fit-content;">
        <div class="box-content">
            <div class="mr-3 ml-5 inner-box">
                <img src="{{ url_for('static', filename='site_images/tommyinnit_pfp.jpg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">TommyInnit</h3>
                <a href="https://www.youtube.com/c/TommyInnit" class="external-link">YouTube</a>
                <p class="m-2" style="font-size: 14px;">
                    "incredibly influential gamer"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    The main channel for Tommy's videos that has amassed
                    over 11 million subscribers. It mainly consists of 
                    Minecraft gameplay with his friends.  
                </p>
            </div>
        </div>
        <div class="box-content" style="position:absolute; left:33%;">
            <div class="mr-3 ml-3 inner-box">
                <img src="{{ url_for('static', filename='site_images/tomsimons_pfp.jpeg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">Tom Simons</h3>
                <a href="https://www.youtube.com/c/TomSimonsVlog" class="external-link">YouTube</a>
                <p class="m-2" style="font-size: 14px;">
                    "the best vlog channel in the history of ever"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    A channel dedicated purely to Tom's vlogs. 
                    He and his friends document their hijinks as they 
                    go on daring adventures across the UK. 
                </p>
            </div>
        </div>
        <div class="box-content" style="position:absolute; left:66%;">
            <div class="mr-4 ml-3 inner-box">
                <img src="{{ url_for('static', filename='site_images/tommyoutit_pfp.jpg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">TommyOutit</h3>
                <a href="https://www.youtube.com/channel/UCgAyQyy6x3L-tmM1GICelGA" class="external-link">YouTube</a>
                <p class="m-2" style="font-size: 14px;">
                    "even more tommyinnit!"
                </p>
                <p class="ml-3 mr-3">
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    A channel for videos that don't fit in the TommyInnit channel.
                </p>
            </div>
        </div>
    </div>
    <div class="row" style="height:fit-content;">
        <div class="box-content" >
            <div class="mr-3 ml-5 inner-box">
                <img src="{{ url_for('static', filename='site_images/tommyvods_pfp.jpg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">TommyVODS</h3>
                <a href="https://www.youtube.com/channel/UC9gVCa6ap-KDayMRPg5wjIg" class="external-link">YouTube</a>
                <p class="m-2" style="font-size: 14px;">
                    "where my full streams are archived & uploaded"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    This channel contains every Twitch stream from 
                    the TommyInnit Twitch channel. 
                </p>
            </div>
        </div>
        <div class="box-content" style="position:absolute; left:33%;">
            <div class="mr-3 ml-3 inner-box">
                <img src="{{ url_for('static', filename='site_images/tomaye_pfp.jpg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">tomaye</h3>
                <a href="https://www.youtube.com/channel/UC6xUVN7hFL43GY9Uz7xQvsg/featured" class="external-link">YouTube</a>
                <p class="m-2" style="font-size: 14px;">
                    "i spend a lot of time editing"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    The forgotten YouTube channel where Tom made group videos with his friends.
                </p>
                
            </div>
        </div>
        <div class="box-content" style="position:absolute; left:66%;">
            <div class="mr-4 ml-3 inner-box">
                <img src="{{ url_for('static', filename='site_images/channelnutpig_pfp.jpg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">Channelnutpig</h3>
                <a href="https://www.youtube.com/c/channelnutpig" class="external-link">YouTube</a>
                <p class="m-2" style="font-size: 14px;">
                    "Most Channel's descriptions are boring! But this one isn't... oh wait... it is :("
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    The original TommyInnit channel originating back in 2013.
                    It contains several of Tom's first videos.
                </p>
            </div>
        </div>
    </div>
    <div class="ribbon-title"><h1>TWITCH</h1></div>
    <div class="row" style="height:fit-content;">
        <div class="box-content">
            <div class="mr-3 ml-5 inner-box">
                <img src="{{ url_for('static', filename='site_images/tommyinnit_pfp.jpg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">tommyinnit</h3>
                <a href="https://www.twitch.tv/tommyinnit" class="external-link">Twitch</a>
                <p class="m-2" style="font-size: 14px;">
                    "incredibly influential gamer"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    Tom's main Twitch channel consists of mainly Minecraft 
                    and Just Chatting content. 
                </p>
            </div>
        </div>
        <div class="box-content" style="position:absolute; left:33%;">
            <div class="mr-3 ml-3 inner-box">
                <img src="{{ url_for('static', filename='site_images/tommyinnitalt_pfp.png')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">tommyinnitalt</h3>
                <a href="https://www.twitch.tv/tommyinnitalt" class="external-link">Twitch</a>
                <p class="m-2" style="font-size: 14px;">
                    "being a big man and hanging out"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    An alt Twitch channel for chill streams. Tom
                    typically streams Animal Crossing here.
                </p>
            </div>
        </div>
        
    </div>
    <div class="ribbon-title"><h1>TWITTER</h1></div>
    <div class="row" style="height:fit-content;">
        <div class="box-content">
            <div class="mr-3 ml-5 inner-box" style="left:33%;">
                <img src="{{ url_for('static', filename='site_images/tommyinnit_pfp.jpg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">@tommyinnit</h3>
                <a href="https://twitter.com/tommyinnit?s=20" class="external-link">Twitter</a>
                <p class="m-2" style="font-size: 14px;">
                    "incredibly influential gamer"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    General Tommy mischief and schenanigans.
                </p>
            </div>
        </div>
        <div class="box-content" style="position:absolute; left:33%;">
            <div class="mr-3 ml-3 inner-box">
                <img src="{{ url_for('static', filename='site_images/tommyaltinnit_pfp.jpeg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">@tommyinnitalt</h3>
                <a href="https://twitter.com/tommyaltinnit?s=20" class="external-link">Twitter</a>
                <p class="m-2" style="font-size: 14px;">
                    "friendly neighourhood INFLUENCER"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    Funny pictures and simple messages.
                </p>
            </div>
        </div>
        <div class="box-content" style="position:absolute; left:66%;">
            <div class="mr-3 ml-3 inner-box">
                <img src="{{ url_for('static', filename='site_images/tomsimons_pfp.jpeg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">@tomsimons</h3>
                <a href="https://twitter.com/tomsimons?s=20" class="external-link">Twitter</a>
                <p class="m-2" style="font-size: 14px;">
                    "incredibly influential vlogger"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    Updates and behind the scenes about Tom's vlogs.
                </p>
            </div>
        </div>
    </div>
    <div class="ribbon-title"><h1>EXTRA</h1></div>
    <div class="row" style="height:fit-content;">
        <div class="box-content">
            <div class="mr-3 ml-5 inner-box" >
                <img src="{{ url_for('static', filename='site_images/tiktok_logo.png')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">@tommyinnit</h3>
                <a href="https://www.tiktok.com/@tommyinnit" class="external-link">TikTok</a>
                <p class="m-2" style="font-size: 14px;">
                    "incredibly influential tiktokker"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    A TikTok channel for short funny goofs and gafs.
                </p>
            </div>
        </div>
        <div class="box-content" style="position:absolute; left:33%;">
            <div class="mr-3 ml-3 inner-box">
                <img src="{{ url_for('static', filename='site_images/spotify_logo.jpeg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">Tommyinnit</h3>
                <a href="https://open.spotify.com/artist/25Ge8p6YT8EwmLTRFtf8Wi?si=LN955n27TM2Uf0EWUtEPWA" class="external-link">Spotify</a>
                <p class="m-2" style="font-size: 14px;">
                    "29,000+ monthly listeners"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    <small>Honestly not sure what's going on here. It's a bit concerning.</small>
                </p>
            </div>
        </div>
        <div class="box-content" style="position:absolute; left:66%;">
            <div class="mr-3 ml-3 inner-box">
                <img src="{{ url_for('static', filename='site_images/instagram_logo.jpeg')}}" class="rounded-circle mt-3" style="filter: drop-shadow(0 0 0.75rem #66202A);">
                <h3 class="mt-1">@tommyinnit</h3>
                <a href="https://www.instagram.com/tommyinnit/" class="external-link">Instagram</a>
                <p class="m-2" style="font-size: 14px;">
                    "incredibly influential gamer"
                </p>
                <p class="ml-3 mr-3" style="padding-bottom: 10px;">
                    Self portraiture.
                </p>
            </div>
        </div>
    </div>

    
    <div class="ribbon" style="background-color: #e3b8b2; position: inherit;"></div>
    <div class="ribbon" style="background-color: #c3848fce; position: inherit;"></div>
</body>
{% endblock content %}

tomplus/templates/main/home.html
{% extends "bases/base_home.html" %}
{% block content %}
<body style="background-color: #eee5d5;">
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
  <script language="javascript" type="text/javascript" src="{{ url_for('static', filename='scripts/site_ids.json')}}"></script>
  <script language="javascript" type="text/javascript" src="{{ url_for('static', filename='scripts/message_randomizer.js')}}"></script>
  <script language="javascript" type="text/javascript" src="{{ url_for('static', filename='scripts/video_selection.js')}}"></script>
  
  
  <!-- home color palette: https://www.color-hex.com/color-palette/7163 -->
  <div style="height: 388px">
    <div class="container-fluid home-bg-img"></div>
    <div class="container-fluid home-bg-text text-center">
      <h1 class="home-title">WELCOME TO TOMPLUS</h1>
      <h3 class="text-uppercase home-title" id="home-message"></h3>
      <div>
        <a class="m-2 home-link" href="{{ url_for('misc.discord') }}">Join the Discord</a>
        <a class="m-2 home-link" href="{{ url_for('misc.merch')}}">Get Some Merch</a>
      </div>
    </div>
  </div>
  <div style="height: 191px">
    <div class="ribbon" style="background-color: #f0ccb8; top:469px;"></div>
    <div class="ribbon" style="background-color: #acccc6; top:569px;"></div>
    <div class="marquee-container below-ribbon">
      <div class="marquee">
        <div class="text">Welcome to TomPlus! One day I'll make this marquee wrap around, I swear.</div>      
      </div>
    </div>
  </div>
  <div style="width: 100%; height: auto;">
    <div class="box" style="background-color: #5a7876;">
      <h1 class="mt-5 ml-4 mr-4 mb-3" style="color: #eee5d5; display: inline-block;">Feeling bored? Watch a Video!</h1>
      <div class="vb-container">
        <div class="row"> <button class="btn mb-3 video-button col-md-12"  onclick="surpriseVid()">Surprise Me!</button> </div>
        <div class="row"> <button class="btn mb-3 video-button col-md-12" onclick="mainVid()">Main Channel</button> </div>
        <div class="row"> <button class="btn mb-3 video-button col-md-12" onclick="vlogVid()">Vlog Adventures</button> </div>
        <div class="row"> <button class="btn mb-3 video-button col-md-12" onclick="twitchVid()">Twitch VODs</button> </div>
      </div>
    </div>
    <div class="box" style="position:absolute; left: 50%; ">
      <div class="video-box" id="player"></div>
    </div> 
  </div>

  <div class="ribbon" style="background-color: #acccc6; position: inherit;"></div>

  <h1 style="color: black; text-align: center; padding-top: 10px;">Featured Fan Art</h1>
  <div class="ribbon" style="background-color: #f0ccb8; position:inherit;"></div>

  <div style="width: 100%; height:35rem; position:relative; text-align: center; background-color: #2c2c2cb4; padding-bottom: 10px;">
    <!-- change to database with picture & artist -->
    {% for art in fanart %}
      <div class="slides"><img class="slides-picture" src="{{ url_for('static', filename='/site_images/fanart/' + art.image) }}"><p style="color:antiquewhite;">{{ art.artist }}</p></div>
    {% endfor %}
    
    <button class="pic-buttons but-display-l"  style="width:10%" onclick="plusDivs(-1)">&#10094;</button>
    <button class="pic-buttons but-display-r" style="width:10%" onclick="plusDivs(+1)">&#10095;</button>
  </div>
  <div class="ribbon" style="background-color: #acccc6; position:inherit;"></div>
  <div class="ribbon" style="background-color: #eee5d5; position:inherit;"></div>
  <div class="ribbon" style="background-color: #f0ccb8; position:inherit;"></div>

  <script>
    var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("slides");
  if (n > x.length) {slideIndex = 1} 
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none"; 
  }
  x[slideIndex-1].style.display = "block"; 
}
  </script>

</body>
    
{% endblock content %}

tomplus/templates/main/lockout.html
{% extends "bases/base_home.html" %}
{% block content %}
    <!-- What shows up if you're not logged-in or are not a twitch sub -->
    <!-- Shouldn't be a route, should be a pop-up, which means I may
        have to add this html to a different file -->
    <div class="fill-page">
        <h1>
            Lockout Page
        </h1>
    </div>

{% endblock content %}