tomplus/main/routes.py
from flask import render_template, request, Blueprint
from tomplus.models import Fanart, Post, TV_Videos

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    fanart = Fanart.query.order_by(Fanart.id)
    return render_template('main/home.html', fanart=fanart)

@main.route("/about")
def about():
    return render_template('main/about.html', title='About')

@main.route("/content")
def content():
    return render_template('main/content.html', title='Content')

@main.route("/announcements")
def announcements():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('main/announcements.html', posts=posts, title='Announcements')

tomplus/users/routes.py
from flask import (render_template, url_for, flash, redirect,
                    request, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required                    
from tomplus import db, bcrypt
from tomplus.models import User, Post, Fanart, TS_Videos
from tomplus.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                    RequestResetForm, ResetPasswordForm, AddFanartForm)
from tomplus.users.utils import save_picture, send_reset_email, save_art

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)

    art_form = AddFanartForm()
    if art_form.image.data:
        artist_image = save_art(art_form.image.data)
        new_art = Fanart(image=artist_image, artist=art_form.artist.data)
        db.session.add(new_art)
        db.session.commit()
        flash('New art added to homepage!', 'success')
        return redirect(url_for('users.account'))

    return render_template('account.html', title='Account',
                           image_file=image_file, form=form, art_form=art_form)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)

    
        
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

tomplus/templates/bases/base.html
<!DOCTYPE html> 
<html> 
    <head>  
      <!-- from getbootstrap.com -->
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">

      {% if title %}
      <title>TOM+ : {{ title }}</title>
      {% else %}
          <title>TOM+</title>
      {% endif %}
    </head>
    <body>
      <!-- Header -->
      <header class="site-header">
        <nav class="navbar navbar-default navbar-expand-md fixed-top" style="background-color: #FF1919;">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="{{ url_for('main.home') }}">
                <img class="banner-image" alt="Brand" style="max-height: 53px;" src="{{ url_for('static', filename='site_images/TOM_logo_3.png') }}">
              </a>
              
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </nav>
      </header>
      
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
          </div>
        </div>
      </main>
      {% block content %}{% endblock %}

      <!-- FOOTER -->
      <div style="background-color: #2c2c2c; height:180px;">
        <div class="ml-3" style="padding-top: 10px;">
          <h1>
            TOM SIMONS
            <div>
              <a href="https://www.instagram.com/tommyinnit/"><img src="{{ url_for('static', filename='site_images/instagram_icon.png') }}" width="32px"></a>
              <a href="https://www.twitch.tv/tommyinnit"><img src="{{ url_for('static', filename='site_images/twitch_icon.png') }}" width="32px" href=""></a>
              <a href="https://www.reddit.com/r/tommyinnit/"><img src="{{ url_for('static', filename='site_images/reddit_icon.png') }}" width="32px" href=""></a>
              <a href="https://www.youtube.com/c/TommyInnit"><img src="{{ url_for('static', filename='site_images/youtube_icon.png') }}" width="32px" href=""></a>
              <a href="https://twitter.com/tommyinnit"><img src="{{ url_for('static', filename='site_images/twitter_icon.png') }}" width="32px" href=""></a>
            </div>
          </h1>
            <p style="padding-top: 25px; color: antiquewhite; font-family: monospace; font-size: 15px;">Created by <a href="https://www.youtube.com/channel/UCGF6Z9CgXHrydlbUKfUjQwQ" style="color:antiquewhite">DEAD HANDS</a></p>
        </div>
      </div>
  
      <!-- Optional JavaScript from getbootstrap.com-->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

tomplus/templates/bases/base_home.html
<!DOCTYPE html> 
<html> 
    <head>  
      <!-- from getbootstrap.com -->
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css')}}">

      {% if title %}
      <title>TOM+ : {{ title }}</title>
      {% else %}
          <title>TOM+</title>
      {% endif %}
    </head>
    <body style="background-color: #eee5d5;">
      <!-- Thinking of having a row above the tabs for some breathing room
        the space could contain a scrolling message bar that says something? -->

      <!-- Header -->
      <header class="site-header">
        <nav class="navbar navbar-default navbar-expand-md fixed-top" style="background-color:#FF1919;">
          <div class="container-fluid">
            <div class="navbar-header navbar-left">
              <a class="navbar-brand" href="{{ url_for('main.home') }}">
                <img class="banner-image" alt="Brand" style="max-height: 53px;" src="{{ url_for('static', filename='site_images/TOM_logo_3.png') }}">
              </a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <!-- <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a> -->
              {% endif %}
            </div>
          </div>
        </nav>
      </header>
      
      <!-- Alerts -->
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
          </div>
        </div>
      </main>

      <!-- Faux header -->
      <a class="col-md-3 selection-tab btn btn-default br-0" href="{{ url_for('main.home') }}" 
      id="Home">HOME</a>
      <a class="col-md-3 selection-tab btn btn-default br-0" href="{{ url_for('main.announcements') }}" 
      id="Announcements">ANNOUNCEMENTS</a>
      <a class="col-md-3 selection-tab btn btn-default br-0" href="{{ url_for('main.content') }}"
      id="Content">CONTENT</a>
      <a class="col-md-3 selection-tab btn btn-default br-0" href="{{ url_for('main.about') }}"
      id="About">ABOUT</a>
      


      {% block content %}{% endblock %}
  

      <!-- FOOTER -->
      <div style="background-color: #2c2c2c; height:180px;">
        <div class="ml-3" style="padding-top: 10px;">
          <h1>
            TOM SIMONS
            <div>
              <a href="https://www.instagram.com/tommyinnit/"><img src="{{ url_for('static', filename='site_images/instagram_icon.png') }}" width="32px"></a>
              <a href="https://www.twitch.tv/tommyinnit"><img src="{{ url_for('static', filename='site_images/twitch_icon.png') }}" width="32px" href=""></a>
              <a href="https://www.reddit.com/r/tommyinnit/"><img src="{{ url_for('static', filename='site_images/reddit_icon.png') }}" width="32px" href=""></a>
              <a href="https://www.youtube.com/c/TommyInnit"><img src="{{ url_for('static', filename='site_images/youtube_icon.png') }}" width="32px" href=""></a>
              <a href="https://twitter.com/tommyinnit"><img src="{{ url_for('static', filename='site_images/twitter_icon.png') }}" width="32px" href=""></a>
            </div>
          </h1>
            <p style="padding-top: 25px; color: antiquewhite; font-family: monospace; font-size: 15px;">Created by <a href="https://www.youtube.com/channel/UCGF6Z9CgXHrydlbUKfUjQwQ" style="color:antiquewhite">DEAD HANDS</a></p>
        </div>
      </div>

      <!-- JavaScript from getbootstrap.com-->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>